import{a}from"./assets/vendor-bdb8a163.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();class d{constructor(t){this.element=document.querySelector(t)}show(){this.element.classList.add("shown")}hide(){this.element.classList.remove("shown")}}const c={loading:new d(".loader"),error:new d(".error")};a.defaults.headers.common["x-api-key"]="live_pMCfR6LBn2xPtA30XNUDqQuzNboweMfLkokOv7CgweK1nlwealH4JxkyIFM711st";a.defaults.timeout=1e3;const f=()=>(c.loading.show(),c.error.hide(),a.get("https://api.thecatapi.com/v1/breeds").then(e=>(console.log({response:e}),e)).then(e=>e.data.map(({id:t,name:n})=>({id:t,name:n}))).catch(e=>{console.error(e),c.error.show()}).finally(()=>{c.loading.hide()})),p=e=>e?(c.loading.show(),c.error.hide(),a.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(t=>t.data[0]).then(t=>{const{url:n,breeds:s}=t,{id:r,name:o,description:l,temperament:h}=s[0];return{id:r,name:o,description:l,temperament:h,image_url:n}}).catch(t=>(console.error(t),c.error.show(),null)).finally(()=>{c.loading.hide()})):null,i={select:document.querySelector(".breed-list"),info:document.querySelector(".breed-info-wrapper")},u="breedList",m=36e5*24,g=e=>{const t=[];e.forEach(({id:n,name:s})=>{const r=document.createElement("option");r.value=n,r.textContent=s,t.push(r)}),i.select.append(...t),i.select.addEventListener("change",y)},y=e=>{e.preventDefault();const t=e.target.value;if(!t){i.info.innerHTML="";return}p(t).then(w).catch(n=>{console.error(n)})},w=({name:e,description:t,temperament:n,image_url:s})=>{const r=`
    <div class="breed-info">
        <img src="${s}" width="300" alt="${e}" class="thumb">
        <div>
            <h1 class="title">${e}</h1>
            <p class="description">${t}</p>
            <p class="temperament">${n}</p>
        </div>
    </div>`;i.info.innerHTML=r},v=e=>{console.log({breedList:e,len:e==null?void 0:e.length}),!(!e||(e==null?void 0:e.length)===0)&&localStorage.setItem(u,JSON.stringify({breedList:e,expire:Date.now()+m}))},E=()=>{const e=localStorage.getItem(u);if(e){const t=JSON.parse(e);if((t==null?void 0:t.expire)>Date.now())return t.breedList}},S=async()=>{let e=[];try{e=await f(),v(e)}catch(t){console.error(t)}return e};(async()=>{let e=E()||await S();g(e)})();
//# sourceMappingURL=commonHelpers.js.map
