import{a as l}from"./assets/vendor-bdb8a163.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();class d{constructor(t){this.element=document.querySelector(t)}show(){this.element.classList.add("shown")}hide(){this.element.classList.remove("shown")}}const c={loading:new d(".loader"),error:new d(".error")};l.defaults.headers.common["x-api-key"]="live_pMCfR6LBn2xPtA30XNUDqQuzNboweMfLkokOv7CgweK1nlwealH4JxkyIFM711st";l.defaults.timeout=1e3;const p=()=>(c.loading.show(),c.error.hide(),l.get("https://api.thecatapi.com/v1/breeds").then(e=>e).then(e=>e.data.map(({id:t,name:o})=>({id:t,name:o}))).catch(e=>{c.error.show()}).finally(()=>{c.loading.hide()})),h=e=>e?(c.loading.show(),c.error.hide(),l.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(t=>t.data[0]).then(t=>{const{url:o,breeds:s}=t,{id:r,name:n,description:i,temperament:f}=s[0];return{id:r,name:n,description:i,temperament:f,image_url:o}}).catch(t=>(c.error.show(),null)).finally(()=>{c.loading.hide()})):null,m="breedList",g=36e5*24,a={section:document.querySelector("body > section"),info:document.querySelector(".breed-info-wrapper")},y=e=>{const t=document.createElement("select");t.name="breed",t.classList.add("breed-list"),e.forEach(({id:o,name:s})=>{const r=document.createElement("option");r.value=o,r.textContent=s,t.append(r)}),a.section.insertAdjacentElement("afterbegin",t),t.addEventListener("change",w)},w=e=>{e.preventDefault(),a.info.innerHTML="";const t=e.target.value;if(!t){u();return}h(t).then(u).catch(o=>{})},u=(e=null)=>{if(!e){a.info.innerHTML="";return}const{name:t,description:o,temperament:s,image_url:r}=e,n=`
    <div class="breed-info">
        <img src="${r}" width="300" alt="${t}" class="thumb">
        <div>
            <h1 class="title">${t}</h1>
            <p class="description">${o}</p>
            <p class="temperament">${s}</p>
        </div>
    </div>`;a.info.innerHTML=n},L=e=>{!e||(e==null?void 0:e.length)===0||localStorage.setItem(m,JSON.stringify({breedList:e,expire:Date.now()+g}))},v=()=>{const e=localStorage.getItem(m);if(e){const t=JSON.parse(e);if((t==null?void 0:t.expire)>Date.now())return t.breedList}},E=async()=>{const e=await p();return L(e),e};(async()=>y(v()||await E()))();
//# sourceMappingURL=commonHelpers.js.map
